### ISSUE TITLE
TERM setting of tmux-256color vs screen…

### ISSUE THREAD

**Issue by kierun** [Qix-/better-exceptions#103]
I run `tmux 3.1` and have set a few `TERM`: with `export TERM=tmux-256color`, I get no colour support in traces, 
whereas with `TERM=screen` I get all the nifty colours.

Here is screenshot:

![screenshot](https://user-images.githubusercontent.com/3079575/87052188-66dc8680-c1f8-11ea-9aed-f4fea7409186.png)

**Comment by ygworldr** [comment]
Any update on this?

**Comment by Qix-** [comment]
@ygworldr https://blog.sindresorhus.com/issue-bumping-e3b9740e2a0

**Comment by kierun** [comment]
`export TERM=tmux` works fine as a work around. The terminal setting appears to support 256 colours. Meh, not ideal but it works…
