### ISSUE TITLE
Don't print stack frames from certain libraries

### ISSUE THREAD

**Issue by riyadparvez** [Qix-/better-exceptions#118]
Is it possible to not print stack frames from third party library? Ideally with a confiuration `ignore=['pandas', 'numpy']` or a function `ignore(['pandas', 'numpy'])`?

**Comment by Qix-** [comment]
Yep, agreed.

Perhaps it would be useful to ignore paths that exist outside of the root of the module entirely, with the ability to enable them in scenarios where it's necessary via an environment variable.

@Delgan (hi! long time 👋🏻 hope you're doing well) what do you think about that idea?

**Comment by Delgan** [comment]
Hey @Qix-! Sorry for this answer a month later, I had taken a little break. :)

Regarding the issue raised here, it looks to me that it has little to do with `better_exceptions` and is rather a problem on `loguru` side. The traceback is displayed entirely which leads to printing undesired frames from third libraries. Using solely `better_exceptions` it would be displayed as follow:

```
Traceback (most recent call last):
  File "python-test/apscheduler-test.py", line 118, in print_greeting
    raise Exception("NOOOOOOOOOOOOOO")
Exception: NOOOOOOOOOOOOOO
```

However, if there exist cases for which `better_exceptions` formatting is considered too verbose, we could indeed imagine a solution to make it more readable. Adding an option to hide external paths seems like a good idea. Another possibility that I think we discussed a few years ago is to highlight the most interesting ones as done by [`tbvaccine`](https://github.com/skorokithakis/tbvaccine/):

![tbvaccine](https://user-images.githubusercontent.com/4193924/143721801-f89fe84d-a095-4882-b12c-5343505590d5.png)

Two others libraries that could be inspiring are [`PrettyErrors`](https://github.com/onelivesleft/PrettyErrors) and [`rich`](https://github.com/willmcgugan/rich).

Anyway, thanks for asking my opinion, I hope you're doing well too!

**Comment by riyadparvez** [comment]
@Delgan I've created a new issue since it's specific to loguru https://github.com/Delgan/loguru/issues/622. I am closing this one.
