### ISSUE TITLE
How to hide sensibles data like passwords, tokens, ...

### ISSUE THREAD

**Issue by max13fr** [Qix-/better-exceptions#119]
Hello,

First, thanks for your really useful package !

I would like to hide secrets data like password, tokens, private_key, ... Do you have any solution ?

I think the best approch is to check the argument name in case of simple structure (str, int, ...) and argument content in case of dict for example, then override the sensitive data by a raw string. Do you know what function I can override ?

I know it would not be perfect, but if we could avoid the majority of the leaking it's already a huge step.

Thanks in advance,
Max

**Comment by Qix-** [comment]
Yeah, don't use this package if you're working with sensitive information. It's not meant to be used in production. There is no other alternative here - anything would be a hack at best, insecure at worst.
