### ISSUE TITLE
Multiple terminfo locations

### ISSUE THREAD

**Issue by pylipp** [Qix-/better-exceptions#15]
I'm on a Ubuntu 16.04 box. Automatic terminfo detection in the `color.py` module didn't work for me. 
There are several `terminfo` directories in my root. 

    find / -type d -name terminfo -print

returns 

    /usr/share/terminfo
    /etc/terminfo
    /lib/terminfo

`/etc/terminfo` contains nothing but a `README` saying 

> This directory is for system-local terminfo descriptions. By default,
> ncurses will search ${HOME}/.terminfo first, then /etc/terminfo (this
> directory), then /lib/terminfo, and last not least /usr/share/terminfo.

Indeed, I found the relevant entry `/lib/terminfo/x/xterm-256color`. The directory `/usr/share/terminfo` is empty. 

I can submit a PR fixing this by iterating over the possible `terminfo` directories in `get_terminfo_file()`, looking for an existing file.

**Comment by Qix-** [comment]
For my own future reference, I _did_ look up how ncurses does it. Turns out they have no standard place for the database either.

**Comment by Qix-** [comment]
Released as `0.1.5`!
