### ISSUE TITLE
Add documentation for Django support to README

### ISSUE THREAD

**Issue by im-n1** [Qix-/better-exceptions#22]
Hi,

thank you for great lib.

However I had no luck to get it working under Django. I tried to put the import into `wsgi.py` or into specific file, where exception is thrown. No luck.

Any ideas?

**Comment by vanadium23** [comment]
@grafa have you try to put in settings.py?

**Comment by the5fire** [comment]
Because Django had handled this. At: https://github.com/django/django/blob/master/django/core/handlers/exception.py#L88

**Comment by grafa** [comment]
@vanadium23 no, haven't had an opportunity yet.
@the5fire so there is no way to plug in the lib into django?

**Comment by Qix-** [comment]
What happens if you enable `settings.DEBUG_PROPAGATE_EXCEPTIONS`? I'm not sure how you do that (I've never used Django before) but that will raise the exception.

**Comment by the5fire** [comment]
@grafa  Yes.

When we run django use command: runserver, It was based on Python built-in modules:wsgiref,
Even we set `settings.DEBUG_PROPAGATE_EXCEPTIONS` config. The `wsgiref` will handle error.

If you want to get more detail of django exception, I think you can take a look at raven-python.

**Comment by the5fire** [comment]
@grafa U can do some tricky like raven-python: https://docs.sentry.io/clients/python/integrations/django/#integration-with-logging

```
'sentry': {
            'level': 'ERROR', # To capture more than ERROR, change to WARNING, INFO, etc.
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',    #  **here**
            'tags': {'custom-tag': 'x'},
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
```

combine logging handler with better-exceptions.

**Comment by Qix-** [comment]
@the5fire would #21 help this, then?

**Comment by the5fire** [comment]
👍 
Yes, I think this is what  @grafa  want.

**Comment by stevanmilic** [comment]
Are there any ideas how this can be used with Django out of the box?
