### ISSUE TITLE
ANSI does not show correctly

### ISSUE THREAD

**Issue by jcrmatos** [Qix-/better-exceptions#23]
Hello,

My env is Win7P x64 w/ SP1, Py 3.5.2 32b and colorama 0.3.7.

Possibly some misconfiguration of my cmd/system but all output from better_exceptions comes out like this

```
C:\Users\JMatos\MEOCloud\Python\dexp\dexp>python dexp.py
Traceback (most recent call last):
  File "dexp.py", line 45, in <module>
    ←[33;1mimport←[m base_dexp as bdexp
  File "C:\Users\JMatos\MEOCloud\Python\dexp\dexp\base_dexp.py", line 14, in <mo
dule>
    ←[33;1mimport←[m configuration as cfg
ImportError: No module named 'configuration'

```

and this

```
(dexp) C:\Users\JMatos\MEOCloud\Python\dexp\dexp>python dexp.py
Traceback (most recent call last):
  File "dexp.py", line 63, in <module>
    start()
    ←[36m-> <function start at 0x05786618>←[m
  File "C:\Users\JMatos\MEOCloud\Python\dexp\dexp\gui_dexp.py", line 536, in sta
rt
    ←[35;1mprint←[m(a + b)
    ←[36m      |   -> 'a'←[m
    ←[36m      -> 2←[m
TypeError: unsupported operand type(s) for +: 'int' and 'str'

```

However, on the same cmd console if I run a small colorama based game I created everything shows correctly (all the colors, brightness, etc.).

Any ideas?

Best regards,

JM

**Comment by Qix-** [comment]
Let me look into this :)

**Comment by Armored-Dragon** [comment]
I think this has to do with cmd. Maybe the encoding is messing up the escape sequence, or it needs to output slightly differently on windows?

**Comment by jcrmatos** [comment]
Hello,

My cmd CP is 850.
Python's locale.getpreferredencoding() output is 'cp1252'.

If it helps, on my colorama game I use these (that work) to show color/brightness and change position:
from colorama import init, Style, Fore, Back
DOCK = Style.BRIGHT + Fore.YELLOW + '===' + Style.RESET_ALL
SEA = (Back.BLUE + ' ' * 51 + Back.RESET)
print(Style.BRIGHT + ''.join(items) + Style.DIM)  # show bright items
print('\x1b[%d;%dH' % (line, col))  # set print pos at line, col
print('\x1b[%d;%dH%s' % (line, col, text))  # print text at pos line, col

Best regards,

JM

**Comment by Qix-** [comment]
Hi - can you try the branch `fix-windows-encoding`?

**Comment by jcrmatos** [comment]
Hello,

I would, but I never used Git.
Is there any way to test without using Git? Can you create a package for 
me to install on Python?

Best regards,

JM

**Comment by Qix-** [comment]
@jcrmatos try

```
pip install https://github.com/qix-/better-exceptions/archive/fix-windows-encoding.tar.gz
```

**Comment by jcrmatos** [comment]
Hello,

It uninstalled version 0.1.6 and installed your tgz file.
when I run the following script
```
import better_exceptions

def a():
    a = 5
    b = 'aaa'
    print(a + b)

a()
```

it returns these errors
```
C:\Users\JMatos\OneDrive\JMatos-P\Desktop>python teste.py
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Python35-32\lib\site-packages\better_exceptions\__init__.py", line 30
5, in excepthook
    write_stream(full_trace)
  File "C:\Python35-32\lib\site-packages\better_exceptions\__init__.py", line 29
4, in write_stream
    STREAM.buffer.write(data)
TypeError: a bytes-like object is required, not 'str'

Original exception was:
Traceback (most recent call last):
  File "teste.py", line 8, in <module>
    a()
  File "teste.py", line 6, in a
    print(a + b)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Best regards,

JM

**Comment by Qix-** [comment]
Alright I'll get to fixing this later today. I'm going to need to fix how ANSI codes are built up.

Thanks for bringing this to my attention :)

**Comment by ethanhs** [comment]
With Windows 10 Anniversary update and above, you can 
```python
import ctypes
kernel32 = ctypes.windll.kernel32
kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
```
(-11 is the standard out constant, 7 is the new ansi color support)

I put this in my better-exceptions hook, made my console cp65001 by default, and modified `__init__.py` as such
```python
try:
    PIPE_CHAR.encode(sys.stdout.encoding)
except UnicodeEncodeError:
    PIPE_CHAR = '|'
    CAP_CHAR = '->'
```
And voila!
![](https://cdn.discordapp.com/attachments/289585903771451392/342522250693574676/unknown.png)
