### ISSUE TITLE
Add production switch

### ISSUE THREAD

**Issue by Qix-** [Qix-/better-exceptions#24]
A few people now have pointed out it'd be neat to have a production switch.

While I personally would remove the `import` statement manually and only use this in debugging, it might be nice to have a production switch as well.

**Comment by Qix-** [comment]
Looking at this again, what constitutes a production flag? `'PRODUCTION' in os.environ`?

**Comment by dserodio** [comment]
From a security perspective, it'd be better to explicitly enable better-exceptions then explicitly disable (which is what a "production switch" would do.

**Comment by Qix-** [comment]
@dserodio While I agree, that would make an extra step for anyone wanting to use `better-exceptions`.

It might be better to leave a production switch out and just keep `better-exceptions` out of your `setup.py` dependencies so if debug code accidentally gets pushed the build will fail (since `better_exceptions` won't be import-able).

**Comment by anntzer** [comment]
You could provide a pth file (similarly to better_exceptions_hook) with something like
```
import os; exec("if os.environ.get('BETTER_EXCEPTIONS'):\n    import better_exceptions")
```
which would remove the need for adding an import statement, remove the need for better_exceptions_hook, and be much easier to switch on or off.

**Comment by Qix-** [comment]
Closing since #48 basically implements what @anntzer is requesting and due to the fact that you _shouldn't_ be using this module in production at all :)
