### ISSUE TITLE
Can this be used in testing?

### ISSUE THREAD

**Issue by jldiaz** [Qix-/better-exceptions#31]
I imported `better_exceptions` into my test, and ran it (both with `nosetests` and "plain" `python`). When the code being tested produces an exception, the standard trace is printed. I guess that testing frameworks are capturing the exceptions somehow.  Would it be possible to tweak something so that better_exceptions is used to report the exceptions?

**Comment by Qix-** [comment]
If plain python isn't catching the exception then there's something affecting it.

How are you reporting exceptions in this code?

**Comment by Qix-** [comment]
Closing due to lack of information.
