### ISSUE TITLE
Enable better exceptions in my app ?

### ISSUE THREAD

**Issue by stuaxo** [Qix-/better-exceptions#56]
Hi,
   Is there an API I can call to enable better exceptions in my app.
It's for Shoebot, where we basically exec python code to make graphics, we already have an home grown exception formatter thingy, but better exceptions looks better to me.

Cheers
S

**Comment by Delgan** [comment]
Hi @stuaxo 

I think you could use the `better_exceptions.format_exception()` function.

```python
import sys, better_exceptions

try:
    a, b = 1, 0
    a / b
except ZeroDivisionError:
    exc, value, tb = sys.exc_info()

print(better_exceptions.format_exception(exc, value, tb))
```
Output:
```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    a / b
    │   └ 0
    └ 1
ZeroDivisionError: integer division or modulo by zero
```

Does it suit your needs?

**Comment by stuaxo** [comment]
Thanks, that's perfect.
