### ISSUE TITLE
Support of exceptions raised in context of the others

### ISSUE THREAD

**Issue by gergelyk** [Qix-/better-exceptions#57]
When following code is used:
`raise Exception('foo') from another_exception` 

better_exception shows only the last exception. It would be beneficial if it could show `another_exception` too. This can be implemented by looking at `__context__` and `__suppress_context__` attributes of the exception. For example:
https://hastebin.com/doyozafeji.py

**Comment by cipri-tom** [comment]
yes, this would be very useful! I was bitten by this recently and couldn't figure out why it was happening

**Comment by Delgan** [comment]
Yeah, I have implemented this in my fork, hopefully I will find some time to merge it upstream in the next few months...

**Comment by Delgan** [comment]
@Qix- This one can be closed too, as this is fixed by #63 😄
