### ISSUE TITLE
improper place of import

### ISSUE THREAD

**Issue by imansh77** [Qix-/better-exceptions#60]
https://github.com/Qix-/better-exceptions/blob/0b135829734ccb12401276defa66d0882be0b93f/better_exceptions/log.py#L9
is there a solid reason to use import after function?!

**Comment by Delgan** [comment]
Yeah, "lazy import" (inside a function) is a technique to reduce overall import time of a library. You don't pay for `import logging` if you don't use `patch()`. But in this case, this can't work as `Logger` and `StreamHandler` are imported from `logging` at module level anyway.

I don't know what @Qix- had in mind while writing this, does it cause you some issue?

**Comment by Qix-** [comment]
I don't know what `StreamHandler` is so someone must have added that line later on. 

Also, `from X import Y` doesn't bring `X` into scope, whereas `import X` does. So simply removing `import logging` would actually break the program.

But @Delgan's explanation is 100% correct :)
