### ISSUE TITLE
Unicode error when stderr is redirected in Python 2.7

### ISSUE THREAD

**Issue by JohnVillalovos** [Qix-/better-exceptions#7]
Ran into this error:

    $ ./tt.py 2>&1 | cat
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/home/openstack/better_exceptions.py", line 194, in excepthook
        print(full_trace, file=sys.stderr)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2502' in position 99: ordinal not in range(128)

    Original exception was:
    Traceback (most recent call last):
      File "./tt.py", line 83, in <module>
        sys.exit(main())
      File "./tt.py", line 40, in main
        raise ValueError("testing")
    ValueError: testing

**Comment by ethanhs** [comment]
Could you try changing line 194 to read `print(full_trace.encode('utf-8'), file=sys.stderr)`. I believe while piping Python defaults to your terminals encoding or ascii or some such thing. That small change should fix it.

**Comment by JohnVillalovos** [comment]
>Could you try changing line 194 to read print(full_trace.encode('utf-8'), file=sys.stderr). I believe while piping Python defaults to your terminals encoding or ascii or some such thing. That small change should fix it.

That fixed it for Python 2.

But for Python 3 it looks like this :(

    $ python3 test.py 2>&1 | cat
    b'Traceback (most recent call last):\n  File "test.py", line 18, in <module>\n    shallow(bar, 15)\n    \xe2\x94\x82       \xe2\x94\x94 2\n    \xe2\x94\x94 <function shallow at 0x7f35891b5f28>\n  File "test.py", line 9, in shallow\n    deep(a + b)\n    \xe2\x94\x82    \xe2\x94\x82   \xe2\x94\x94 15\n    \xe2\x94\x82    \xe2\x94\x94 2\n    \xe2\x94\x94 <function deep at 0x7f35811347b8>\n  File "test.py", line 14, in deep\n    assert val > 10 and foo == 60\n           \xe2\x94\x82            \xe2\x94\x94 52\n           \xe2\x94\x94 17\nAssertionError: assert val > 10 and foo == 60'

All on one line.

**Comment by Qix-** [comment]
Just out of curiosity, what does `$ echo $LANG` say? :)

**Comment by JohnVillalovos** [comment]
LANG=en_US.UTF-8

**Comment by Qix-** [comment]
Actually, what about `$ echo $LC_ALL`?

Also, what's your terminal?

Fix is inbound for this btw. I've reproduced.

**Comment by JohnVillalovos** [comment]
Nothing for LC_ALL

Using MobaXterm and using Gnome Terminal on Fedora 25.

**Comment by Qix-** [comment]
Can you try using the `fix-encoding` branch?

**Comment by JohnVillalovos** [comment]
Works for me. Thanks!

**Comment by Qix-** [comment]
Going to wait for #8 to resolve (it has a pending fix) before I release again.

Thanks for the report!

**Comment by Qix-** [comment]
Released as `0.1.4`.
