### ISSUE TITLE
Attribute inspection

### ISSUE THREAD

**Issue by gergelyk** [Qix-/better-exceptions#71]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/Qix-/better-exceptions/issues/71)

Hi. This is not an issue. Rather an improvement proposal. I thought that it may be useful if better_exceptions could show values of attributes accessed by period operator.

For instance, instead of:

```
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    print(123 / X.y)
                └ <class '__main__.X'>
ZeroDivisionError: division by zero
```

we would get:

```
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    print(123 / X.y)
                | └ 0
                └ <class '__main__.X'>
ZeroDivisionError: division by zero
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#94 add attribute inspection + test (#71)](https://issuehunt.io/r/Qix-/better-exceptions/pull/94)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/Qix-/better-exceptions/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Qix-** [comment]
Interesting. I worry about the side effects of property access, however - since it's not just a lookup but potentially a function call, which means we'd also have to check for true property access beforehand.

But yeah, I think this could be done safely.

**Comment by gergelyk** [comment]
Good point.

Potential site effects of __getattr__ could be eliminated if we inspect only attributes from __dict__ of the object (and its class, and parent classes of this class). But __getattribute__ still may cause problems.

On the other hand, better_exceptions already calls __repr__ which theoretically also can have site effects. So general safety is violated anyway.

**Comment by Qix-** [comment]
> could be eliminated if we inspect only attributes from `__dict__`

That's what I was thinking. `inspect.getattr_static` would do nicely here.

> On the other hand, better_exceptions already calls `__repr__` which theoretically also can have side effects. So general safety is violated anyway.

Yes but `__repr__` having side effects isn't necessarily a good idea anyway, IMO. I don't really care about that.

**Comment by gergelyk** [comment]
`inspect.getattr_static` - good finding. I agree regarding `__repr__`.

**Comment by blueyed** [comment]
Re `repr()` I've created https://github.com/Qix-/better-exceptions/issues/85 - I think better-exceptions should not crash through it.

**Comment by lokesh1729** [comment]
@Qix- @gergelyk any update on this??
