### ISSUE TITLE
Color support for non-xterm terminals

### ISSUE THREAD

**Issue by philer** [Qix-/better-exceptions#8]
The nocolor check is a bit too strict:
```python
NOCOLOR = not os.isatty(2) or os.name == 'nt' or os.getenv('TERM', '')[:5] != 'xterm'
```
There are a lot of terminals that don't set their TERM env to xterm but support colors (e.g. TERM=urxvt-unicode-256color), including the TTYs on many systems. I'd suggest omitting the TERM check or limiting it to a few common excludes.

---
PS: If anyone else uses a terminal where color support is blocked (like urxvt) you can work around it by explicitly overwriting the NOCOLOR variable:
```python
import better_exceptions
better_exceptions.NOCOLOR = False
```

**Comment by Qix-** [comment]
Yep, I'll do a proper fix for this sometime today.

**Comment by Qix-** [comment]
Does the branch `fix-colors` work for you? :)

**Comment by Qix-** [comment]
@philer could you test the latest on `fix-colors`?

**Comment by Qix-** [comment]
I tested personally in Windows. Other than the above bug, this is working for all terminals (not just xterm).

Any problems with the new detection method should go into a new ticket :)

Released as `0.1.4`.

**Comment by pylipp** [comment]
Just some quick notes: In 0.1.4, `NOCOLOR` was replaced by `SUPPORTS_COLOR`. 
@philer's method then transforms to
    
    import better_exceptions
    better_exceptions.SUPPORTS_COLOR = True

Alternatively, one can set the environment variable `FORCE_COLOR` to 1:

    export FORCE_COLOR=1

**Comment by philer** [comment]
@Qix- Yeah that works. Thanks for the fast fix!
